name: Smart Deploy on Notion Change

on:
  schedule:
    - cron: "0 * * * *"  # 每小时检查一次
  workflow_dispatch:

jobs:
  check_notion_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore previous hash from cache
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: previous.md5
          key: notion-md5-cache

      - name: Fetch Notion Page
        run: |
          curl -s https://buttered-fortnight-727.notion.site/24ee6481ffbd80e299a8c77c37baf01b?v=24ee6481ffbd812b9822000cf768a14c > notion.html

      - name: Generate current hash
        run: |
          md5sum notion.html > current.md5

      - name: Compare hashes and deploy if changed
        run: |
          if [ -f previous.md5 ] && cmp -s current.md5 previous.md5; then
            echo "✅ No changes in Notion content. Skipping deploy."
          else
            echo "🚀 Content changed. Triggering EdgeOne deploy..."
            curl -X POST https://pages-api.edgeone.ai/v1/webhook/32d294f9005676799bb75b8f806a098799f96995e80a9cd1c924f8515c3eba5e
            cp current.md5 previous.md5
          fi

      - name: Save updated hash to cache
        uses: actions/cache@v3
        with:
          path: previous.md5
          key: notion-md5-cache
