name: Deploy NotionNext

on:
  schedule:
    - cron: '*/30 * * * *'  # 每 30 分钟检查一次
  workflow_dispatch:        # 手动触发

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # 保留完整提交历史，避免冲突

      - name: 🔍 Check Notion page hash and deploy if changed
        run: |
          set -euo pipefail
          mkdir -p .cache

          echo "🔄 Pull latest repo to ensure .cache sync..."
          git pull --ff-only || true

          echo "🧾 Calculating current hash..."
          current_hash=$(curl -s https://notion-api.splitbee.io/v1/page/24ee6481ffbd80e299a8c77c37baf01b | md5sum | cut -d ' ' -f1)
          echo "$current_hash" > .cache/current.md5

          echo "📦 Fetching previous hash..."
          if [ ! -f .cache/previous.md5 ]; then
            echo "⚠️ No previous hash found. This is the first run."
          fi

          if [ -f .cache/previous.md5 ] && cmp -s .cache/current.md5 .cache/previous.md5; then
            echo "✅ No content change. Skipping deploy."
            exit 0
          fi

          echo "🚀 Content changed. Triggering EdgeOne deploy..."
          curl -X POST https://pages-api.edgeone.ai/v1/webhook/32d294f9005676799bb75b8f806a098799f96995e80a9cd1c924f8515c3eba5e

          echo "📝 Saving new hash to repo..."
          cp .cache/current.md5 .cache/previous.md5

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

          git add .cache
          git commit -m "🔄 Update previous.md5 after deploy" || echo "No changes to commit"
          git push
