name: Deploy NotionNext

on:
  schedule:
    - cron: '0 * * * *'  # 每 30 分钟检查一次
  workflow_dispatch:        # 支持手动触发

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: 🔍 Check Notion page hash and deploy if changed
        run: |
          mkdir -p .cache

          echo "🔍 Calculating current hash..."
          current_hash=$(curl -s https://notion-api.splitbee.io/v1/page/24ee6481ffbd80e299a8c77c37baf01b | md5sum | cut -d ' ' -f1)
          echo "$current_hash" > .cache/current.md5

          echo "📦 Fetching previous hash from GitHub..."
          curl -s -o .cache/previous.md5 https://raw.githubusercontent.com/ThereChenSnow/NotionNext/main/.cache/previous.md5

          if [ ! -s .cache/previous.md5 ]; then
            echo "⚠️ No previous hash found. Assuming first run. Skipping deploy."
            exit 0
          fi

          previous_hash=$(cat .cache/previous.md5)
          if [ "$current_hash" != "$previous_hash" ]; then
            echo "🚀 Content changed. Triggering EdgeOne deploy..."
            curl -X POST https://pages-api.edgeone.ai/v1/webhook/32d294f9005676799bb75b8f806a098799f96995e80a9cd1c924f8515c3eba5e
          
            # 更新 previous.md5
            cp .cache/current.md5 .cache/previous.md5
            git add .cache/previous.md5
            git commit -m "🔄 Update previous.md5 after deploy"
            git push
          else
            echo "✅ No content change. Skipping deploy."
          fi




