- name: 检测并部署
  run: |
    set -euo pipefail
    mkdir -p .cache

    echo "生成当前 hash..."
    curl -s https://notion-api.splitbee.io/v1/page/24ee6481ffbd80e299a8c77c37baf01b | md5sum | cut -d ' ' -f1 > .cache/current.md5

    echo "获取之前的 hash..."
    curl -s -o .cache/previous.md5 https://raw.githubusercontent.com/ThereChenSnow/NotionNext/main/.cache/previous.md5 || true

    if [ -s .cache/previous.md5 ] && cmp -s .cache/current.md5 .cache/previous.md5; then
      echo "✅ 内容无变化，跳过部署"
      exit 0
    fi

    echo "🚀 检测到更新，调用 EdgeOne webhook..."
    curl -X POST https://pages-api.edgeone.ai/v1/webhook/32d294f9005676799bb75b8f806a098799f96995e80a9cd1c924f8515c3eba5e

    echo "更新并提交 hash..."
    cp .cache/current.md5 .cache/previous.md5
    git config --global user.name "github-actions"
    git config --global user.email "github-actions@users.noreply.github.com"
    git pull --ff-only || true
    git add .cache/previous.md5
    git commit -m "更新 Notion hash [skip ci]" || echo "无改动可提交"
    git push || true
