name: Smart Deploy on Notion Change

on:
  schedule:
    - cron: "0 * * * *"  # 每小时检查一次
  workflow_dispatch:

jobs:
  check_notion_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore previous hash from artifact
        id: restore-hash
        run: |
          mkdir -p .cache
          curl -s -o .cache/previous.md5 https://raw.githubusercontent.com/${{ github.repository }}/main/.cache/previous.md5 || echo "No previous hash found"

      - name: Fetch Notion Page
        run: |
          curl -s https://buttered-fortnight-727.notion.site/24ee6481ffbd80e299a8c77c37baf01b?v=24ee6481ffbd812b9822000cf768a14c > notion.html

      - name: Generate current hash
        run: |
          md5sum notion.html | awk '{print $1}' > current.md5

      - name: Compare hashes and deploy if changed
        run: |
          if [ -f .cache/previous.md5 ] && cmp -s current.md5 .cache/previous.md5; then
            echo "✅ No changes in Notion content. Skipping deploy."
          else
            echo "🚀 Content changed. Triggering EdgeOne deploy..."
            curl -X POST https://pages-api.edgeone.ai/v1/webhook/32d294f9005676799bb75b8f806a098799f96995e80a9cd1c924f8515c3eba5e
            cp current.md5 .cache/previous.md5
          fi

      - name: Commit updated hash
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git pull
          mkdir -p .cache
          cp .cache/previous.md5 .cache/previous.md5
          git add .cache/previous.md5
          git commit -m "Update Notion hash [skip ci]" || echo "No changes to commit"
          git push
