name: Notion Auto Update

on:
  schedule:
    - cron: "*/10 * * * *"  # 每10分钟执行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check Notion Updates and Trigger Build
        run: |
          # === 配置区 ===
          NOTION_TOKEN="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"
          NOTION_DATABASE_ID="24ee6481ffbd80e299a8c77c37baf01b"
          EDGEONE_WEBHOOK="https://pages-api.edgeone.ai/v1/webhook/32d294f9005676799bb75b8f806a098799f96995e80a9cd1c924f8515c3eba5e"
          # =============

          echo "Checking Notion for updates..."
          LAST_EDITED=$(curl -s "https://api.notion.com/v1/databases/$NOTION_DATABASE_ID/query" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            | jq -r '.results[0].last_edited_time')

          echo "Last edited: $LAST_EDITED"

          if [ -f last_update.txt ]; then
            PREV_EDITED=$(cat last_update.txt)
          else
            PREV_EDITED=""
          fi

          if [ "$LAST_EDITED" != "$PREV_EDITED" ]; then
            echo "Detected change in Notion. Triggering EdgeOne build..."
            curl -X POST "$EDGEONE_WEBHOOK"
            echo "$LAST_EDITED" > last_update.txt
          else
            echo "No change detected. Skipping build."
          fi
